--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13 (Homebrew)
-- Dumped by pg_dump version 16.13 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(12) NOT NULL,
    status character varying(9) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id uuid
);


--
-- Name: app_users_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users_groups (
    id bigint NOT NULL,
    appuser_id uuid NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: app_users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_users_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users_user_permissions (
    id bigint NOT NULL,
    appuser_id uuid NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: app_users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_attachments (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    application_type character varying(20) NOT NULL,
    institution_application_number character varying(120),
    file character varying(100) NOT NULL,
    file_name character varying(255) NOT NULL,
    district_id bigint,
    public_entry_id bigint,
    uploaded_by_id uuid,
    drive_file_id character varying(255) NOT NULL,
    drive_mime_type character varying(255) NOT NULL,
    drive_view_url character varying(200) NOT NULL
);


--
-- Name: application_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    article_name character varying(255) NOT NULL,
    article_name_tk character varying(255),
    cost_per_unit numeric(14,2) NOT NULL,
    item_type character varying(20) NOT NULL,
    category character varying(200),
    master_category character varying(200),
    comments text,
    is_active boolean NOT NULL,
    combo boolean NOT NULL
);


--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    action_type character varying(16) NOT NULL,
    entity_type character varying(100) NOT NULL,
    entity_id character varying(120),
    details jsonb NOT NULL,
    ip_address character varying(64),
    user_agent character varying(255),
    user_id uuid
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dashboard_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dashboard_settings (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    event_budget numeric(16,2) NOT NULL,
    updated_by_id uuid
);


--
-- Name: dashboard_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dashboard_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dashboard_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: district_beneficiary_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.district_beneficiary_entries (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    application_number character varying(120),
    article_cost_per_unit numeric(14,2) NOT NULL,
    quantity integer NOT NULL,
    total_amount numeric(16,2) NOT NULL,
    notes text,
    status character varying(10) NOT NULL,
    article_id bigint NOT NULL,
    created_by_id uuid,
    district_id bigint NOT NULL,
    fund_request_id bigint,
    cheque_rtgs_in_favour character varying(255),
    internal_notes text,
    name_of_institution character varying(255),
    aadhar_number character varying(20),
    name_of_beneficiary character varying(255),
    item_comes_here boolean,
    CONSTRAINT district_beneficiary_entries_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: district_beneficiary_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.district_beneficiary_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.district_beneficiary_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: district_master; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.district_master (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    district_name character varying(255) NOT NULL,
    allotted_budget numeric(16,2) NOT NULL,
    president_name character varying(255) NOT NULL,
    mobile_number character varying(50) NOT NULL,
    application_number character varying(120) NOT NULL,
    is_active boolean NOT NULL
);


--
-- Name: district_master_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.district_master ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.district_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: event_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_sessions (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    session_name character varying(120) NOT NULL,
    event_year integer NOT NULL,
    is_active boolean NOT NULL,
    notes text,
    phase2_grouped_quantity_total integer NOT NULL,
    phase2_grouped_row_count integer NOT NULL,
    phase2_source_name character varying(255),
    phase2_source_quantity_total integer NOT NULL,
    phase2_source_row_count integer NOT NULL,
    phase2_reconciliation_snapshot jsonb NOT NULL,
    CONSTRAINT event_sessions_event_year_check CHECK ((event_year >= 0)),
    CONSTRAINT event_sessions_phase2_grouped_quantity_total_check CHECK ((phase2_grouped_quantity_total >= 0)),
    CONSTRAINT event_sessions_phase2_grouped_row_count_check CHECK ((phase2_grouped_row_count >= 0)),
    CONSTRAINT event_sessions_phase2_source_quantity_total_check CHECK ((phase2_source_quantity_total >= 0)),
    CONSTRAINT event_sessions_phase2_source_row_count_check CHECK ((phase2_source_row_count >= 0))
);


--
-- Name: event_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_request (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    fund_request_type character varying(20) NOT NULL,
    fund_request_number character varying(80),
    status character varying(12) NOT NULL,
    total_amount numeric(16,2) NOT NULL,
    aid_type character varying(255),
    notes text,
    gst_number character varying(64),
    supplier_name character varying(255),
    supplier_address text,
    supplier_city character varying(120),
    supplier_state character varying(120),
    supplier_pincode character varying(20),
    purchase_order_number character varying(80),
    created_by_id uuid
);


--
-- Name: fund_request_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_request_articles (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    sl_no integer,
    beneficiary text,
    article_name character varying(255) NOT NULL,
    gst_no character varying(64),
    quantity integer NOT NULL,
    unit_price numeric(14,2) NOT NULL,
    price_including_gst numeric(14,2) NOT NULL,
    value numeric(16,2) NOT NULL,
    cumulative numeric(16,2) NOT NULL,
    cheque_in_favour character varying(255),
    cheque_no character varying(120),
    supplier_article_name character varying(255),
    description text,
    article_id bigint NOT NULL,
    fund_request_id bigint NOT NULL,
    vendor_id bigint,
    vendor_address text,
    vendor_city character varying(120),
    vendor_name character varying(255),
    vendor_pincode character varying(20),
    vendor_state character varying(120),
    CONSTRAINT fund_request_articles_quantity_check CHECK ((quantity >= 0)),
    CONSTRAINT fund_request_articles_sl_no_check CHECK ((sl_no >= 0))
);


--
-- Name: fund_request_articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fund_request_articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_request_articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund_request_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_request_documents (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    document_type character varying(20) NOT NULL,
    file_path text,
    file_name character varying(255) NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    fund_request_id bigint NOT NULL,
    generated_by_id uuid
);


--
-- Name: fund_request_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fund_request_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_request_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund_request_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fund_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund_request_recipients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_request_recipients (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    beneficiary_type character varying(20),
    beneficiary text,
    recipient_name character varying(255) NOT NULL,
    name_of_beneficiary character varying(255),
    name_of_institution character varying(255),
    details text,
    fund_requested numeric(14,2) NOT NULL,
    aadhar_number character varying(20),
    address text,
    cheque_in_favour character varying(255),
    cheque_no character varying(120),
    notes text,
    district_name character varying(255),
    fund_request_id bigint NOT NULL,
    source_entry_id integer,
    CONSTRAINT fund_request_recipients_source_entry_id_check CHECK ((source_entry_id >= 0))
);


--
-- Name: fund_request_recipients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fund_request_recipients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_request_recipients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: institutions_beneficiary_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.institutions_beneficiary_entries (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    institution_name character varying(255) NOT NULL,
    institution_type character varying(20) NOT NULL,
    application_number character varying(120),
    address text,
    mobile character varying(50),
    article_cost_per_unit numeric(14,2) NOT NULL,
    quantity integer NOT NULL,
    total_amount numeric(16,2) NOT NULL,
    notes text,
    status character varying(10) NOT NULL,
    article_id bigint NOT NULL,
    created_by_id uuid,
    fund_request_id bigint,
    cheque_rtgs_in_favour character varying(255),
    internal_notes text,
    name_of_institution character varying(255),
    aadhar_number character varying(20),
    name_of_beneficiary character varying(255),
    item_comes_here boolean,
    CONSTRAINT institutions_beneficiary_entries_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: institutions_beneficiary_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.institutions_beneficiary_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.institutions_beneficiary_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: label_generation_rows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.label_generation_rows (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    source_file_name character varying(255),
    application_number character varying(120),
    beneficiary_name character varying(255),
    requested_item character varying(255),
    beneficiary_type character varying(30),
    sequence_no integer,
    start_token_no integer,
    end_token_no integer,
    row_data jsonb NOT NULL,
    headers jsonb NOT NULL,
    sort_order integer NOT NULL,
    created_by_id uuid,
    session_id bigint NOT NULL,
    updated_by_id uuid,
    CONSTRAINT label_generation_rows_end_token_no_check CHECK ((end_token_no >= 0)),
    CONSTRAINT label_generation_rows_sequence_no_check CHECK ((sequence_no >= 0)),
    CONSTRAINT label_generation_rows_sort_order_check CHECK ((sort_order >= 0)),
    CONSTRAINT label_generation_rows_start_token_no_check CHECK ((start_token_no >= 0))
);


--
-- Name: label_generation_rows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.label_generation_rows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.label_generation_rows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_entries (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    quantity_ordered integer NOT NULL,
    order_date date NOT NULL,
    status character varying(10) NOT NULL,
    supplier_name character varying(255),
    supplier_contact character varying(120),
    unit_price numeric(14,2),
    total_amount numeric(16,2) NOT NULL,
    expected_delivery_date date,
    notes text,
    article_id bigint NOT NULL,
    created_by_id uuid,
    fund_request_id bigint,
    CONSTRAINT order_entries_quantity_ordered_check CHECK ((quantity_ordered >= 0))
);


--
-- Name: order_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: public_beneficiary_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_beneficiary_entries (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    application_number character varying(120),
    name character varying(255) NOT NULL,
    aadhar_number character varying(20) NOT NULL,
    is_handicapped character varying(80) NOT NULL,
    gender character varying(15),
    female_status character varying(80),
    address text,
    mobile character varying(50),
    article_cost_per_unit numeric(14,2) NOT NULL,
    quantity integer NOT NULL,
    total_amount numeric(16,2) NOT NULL,
    notes text,
    status character varying(10) NOT NULL,
    article_id bigint NOT NULL,
    created_by_id uuid,
    fund_request_id bigint,
    cheque_rtgs_in_favour character varying(255),
    name_of_institution character varying(255),
    item_comes_here boolean,
    CONSTRAINT public_beneficiary_entries_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: public_beneficiary_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_beneficiary_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_beneficiary_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: public_beneficiary_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_beneficiary_history (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    aadhar_number character varying(20) NOT NULL,
    name character varying(255) NOT NULL,
    year integer NOT NULL,
    article_name character varying(255),
    application_number character varying(120),
    comments text,
    is_handicapped boolean,
    address text,
    mobile character varying(50),
    aadhar_number_sp character varying(20),
    is_selected boolean,
    category character varying(120),
    CONSTRAINT public_beneficiary_history_year_check CHECK ((year >= 0))
);


--
-- Name: public_beneficiary_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_beneficiary_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_beneficiary_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_order (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    purchase_order_number character varying(80),
    status character varying(12) NOT NULL,
    vendor_name character varying(255) NOT NULL,
    vendor_address text NOT NULL,
    vendor_city character varying(120) NOT NULL,
    vendor_state character varying(120) NOT NULL,
    vendor_pincode character varying(20) NOT NULL,
    total_amount numeric(16,2) NOT NULL,
    created_by_id uuid,
    comments text,
    gst_number character varying(64)
);


--
-- Name: purchase_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchase_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_order_items (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    article_name character varying(255) NOT NULL,
    supplier_article_name character varying(255) NOT NULL,
    description text,
    quantity integer NOT NULL,
    unit_price numeric(14,2) NOT NULL,
    total_value numeric(16,2) NOT NULL,
    article_id bigint NOT NULL,
    purchase_order_id bigint NOT NULL,
    CONSTRAINT purchase_order_items_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: purchase_order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchase_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seat_allocation_rows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seat_allocation_rows (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    source_file_name character varying(255),
    application_number character varying(120),
    beneficiary_name character varying(255),
    district character varying(255),
    requested_item character varying(255) NOT NULL,
    quantity integer NOT NULL,
    waiting_hall_quantity integer NOT NULL,
    token_quantity integer NOT NULL,
    beneficiary_type character varying(30),
    item_type character varying(30),
    comments text,
    master_row jsonb NOT NULL,
    master_headers jsonb NOT NULL,
    sort_order integer NOT NULL,
    sequence_no integer,
    created_by_id uuid,
    session_id bigint NOT NULL,
    updated_by_id uuid,
    CONSTRAINT seat_allocation_rows_quantity_check CHECK ((quantity >= 0)),
    CONSTRAINT seat_allocation_rows_sequence_no_check CHECK ((sequence_no >= 0)),
    CONSTRAINT seat_allocation_rows_sort_order_check CHECK ((sort_order >= 0)),
    CONSTRAINT seat_allocation_rows_token_quantity_check CHECK ((token_quantity >= 0)),
    CONSTRAINT seat_allocation_rows_waiting_hall_quantity_check CHECK ((waiting_hall_quantity >= 0))
);


--
-- Name: seat_allocation_rows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seat_allocation_rows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seat_allocation_rows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sequence_list_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sequence_list_items (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    item_name character varying(255) NOT NULL,
    sequence_no integer NOT NULL,
    sort_order integer NOT NULL,
    created_by_id uuid,
    session_id bigint NOT NULL,
    updated_by_id uuid,
    CONSTRAINT sequence_list_items_sequence_no_check CHECK ((sequence_no >= 0)),
    CONSTRAINT sequence_list_items_sort_order_check CHECK ((sort_order >= 0))
);


--
-- Name: sequence_list_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sequence_list_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_list_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_generation_rows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_generation_rows (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    source_file_name character varying(255),
    application_number character varying(120),
    beneficiary_name character varying(255),
    requested_item character varying(255),
    beneficiary_type character varying(30),
    sequence_no integer,
    start_token_no integer,
    end_token_no integer,
    row_data jsonb NOT NULL,
    headers jsonb NOT NULL,
    sort_order integer NOT NULL,
    created_by_id uuid,
    session_id bigint NOT NULL,
    updated_by_id uuid,
    CONSTRAINT token_generation_rows_end_token_no_check CHECK ((end_token_no >= 0)),
    CONSTRAINT token_generation_rows_sequence_no_check CHECK ((sequence_no >= 0)),
    CONSTRAINT token_generation_rows_sort_order_check CHECK ((sort_order >= 0)),
    CONSTRAINT token_generation_rows_start_token_no_check CHECK ((start_token_no >= 0))
);


--
-- Name: token_generation_rows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_generation_rows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_generation_rows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_module_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_module_permissions (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    module_key character varying(64) NOT NULL,
    can_view boolean NOT NULL,
    can_create_edit boolean NOT NULL,
    can_delete boolean NOT NULL,
    can_submit boolean NOT NULL,
    can_export boolean NOT NULL,
    can_upload_replace boolean NOT NULL,
    can_reset_password boolean NOT NULL,
    user_id uuid NOT NULL,
    can_reopen boolean NOT NULL
);


--
-- Name: user_module_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_module_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_module_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vendors (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    vendor_name character varying(255) NOT NULL,
    gst_number character varying(64),
    address text,
    city character varying(120),
    state character varying(120),
    pincode character varying(20),
    cheque_in_favour character varying(255),
    is_active boolean NOT NULL
);


--
-- Name: vendors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vendors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_users app_users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_email_key UNIQUE (email);


--
-- Name: app_users_groups app_users_groups_appuser_id_group_id_e7e72515_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users_groups
    ADD CONSTRAINT app_users_groups_appuser_id_group_id_e7e72515_uniq UNIQUE (appuser_id, group_id);


--
-- Name: app_users_groups app_users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users_groups
    ADD CONSTRAINT app_users_groups_pkey PRIMARY KEY (id);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: app_users_user_permissions app_users_user_permissio_appuser_id_permission_id_9680e778_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users_user_permissions
    ADD CONSTRAINT app_users_user_permissio_appuser_id_permission_id_9680e778_uniq UNIQUE (appuser_id, permission_id);


--
-- Name: app_users_user_permissions app_users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users_user_permissions
    ADD CONSTRAINT app_users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: application_attachments application_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_attachments
    ADD CONSTRAINT application_attachments_pkey PRIMARY KEY (id);


--
-- Name: articles articles_article_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_article_name_key UNIQUE (article_name);


--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: dashboard_settings dashboard_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dashboard_settings
    ADD CONSTRAINT dashboard_settings_pkey PRIMARY KEY (id);


--
-- Name: district_beneficiary_entries district_beneficiary_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district_beneficiary_entries
    ADD CONSTRAINT district_beneficiary_entries_pkey PRIMARY KEY (id);


--
-- Name: district_master district_master_district_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district_master
    ADD CONSTRAINT district_master_district_name_key UNIQUE (district_name);


--
-- Name: district_master district_master_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district_master
    ADD CONSTRAINT district_master_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: event_sessions event_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_sessions
    ADD CONSTRAINT event_sessions_pkey PRIMARY KEY (id);


--
-- Name: event_sessions event_sessions_session_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_sessions
    ADD CONSTRAINT event_sessions_session_name_key UNIQUE (session_name);


--
-- Name: fund_request_articles fund_request_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request_articles
    ADD CONSTRAINT fund_request_articles_pkey PRIMARY KEY (id);


--
-- Name: fund_request_documents fund_request_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request_documents
    ADD CONSTRAINT fund_request_documents_pkey PRIMARY KEY (id);


--
-- Name: fund_request fund_request_fund_request_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request
    ADD CONSTRAINT fund_request_fund_request_number_key UNIQUE (fund_request_number);


--
-- Name: fund_request fund_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request
    ADD CONSTRAINT fund_request_pkey PRIMARY KEY (id);


--
-- Name: fund_request_recipients fund_request_recipients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request_recipients
    ADD CONSTRAINT fund_request_recipients_pkey PRIMARY KEY (id);


--
-- Name: institutions_beneficiary_entries institutions_beneficiary_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.institutions_beneficiary_entries
    ADD CONSTRAINT institutions_beneficiary_entries_pkey PRIMARY KEY (id);


--
-- Name: label_generation_rows label_generation_rows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.label_generation_rows
    ADD CONSTRAINT label_generation_rows_pkey PRIMARY KEY (id);


--
-- Name: order_entries order_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_entries
    ADD CONSTRAINT order_entries_pkey PRIMARY KEY (id);


--
-- Name: public_beneficiary_entries public_beneficiary_entries_application_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_beneficiary_entries
    ADD CONSTRAINT public_beneficiary_entries_application_number_key UNIQUE (application_number);


--
-- Name: public_beneficiary_entries public_beneficiary_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_beneficiary_entries
    ADD CONSTRAINT public_beneficiary_entries_pkey PRIMARY KEY (id);


--
-- Name: public_beneficiary_history public_beneficiary_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_beneficiary_history
    ADD CONSTRAINT public_beneficiary_history_pkey PRIMARY KEY (id);


--
-- Name: purchase_order_items purchase_order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_order_items
    ADD CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id);


--
-- Name: purchase_order purchase_order_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_order
    ADD CONSTRAINT purchase_order_pkey PRIMARY KEY (id);


--
-- Name: purchase_order purchase_order_purchase_order_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_order
    ADD CONSTRAINT purchase_order_purchase_order_number_key UNIQUE (purchase_order_number);


--
-- Name: seat_allocation_rows seat_allocation_rows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seat_allocation_rows
    ADD CONSTRAINT seat_allocation_rows_pkey PRIMARY KEY (id);


--
-- Name: sequence_list_items sequence_list_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_list_items
    ADD CONSTRAINT sequence_list_items_pkey PRIMARY KEY (id);


--
-- Name: token_generation_rows token_generation_rows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_generation_rows
    ADD CONSTRAINT token_generation_rows_pkey PRIMARY KEY (id);


--
-- Name: sequence_list_items uniq_sequence_item_per_session; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_list_items
    ADD CONSTRAINT uniq_sequence_item_per_session UNIQUE (session_id, item_name);


--
-- Name: sequence_list_items uniq_sequence_no_per_session; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_list_items
    ADD CONSTRAINT uniq_sequence_no_per_session UNIQUE (session_id, sequence_no);


--
-- Name: user_module_permissions unique_user_module_permission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_module_permissions
    ADD CONSTRAINT unique_user_module_permission UNIQUE (user_id, module_key);


--
-- Name: user_module_permissions user_module_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_module_permissions
    ADD CONSTRAINT user_module_permissions_pkey PRIMARY KEY (id);


--
-- Name: vendors vendors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_pkey PRIMARY KEY (id);


--
-- Name: app_users_created_by_id_b75edff3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_users_created_by_id_b75edff3 ON public.app_users USING btree (created_by_id);


--
-- Name: app_users_email_51eb7249_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_users_email_51eb7249_like ON public.app_users USING btree (email varchar_pattern_ops);


--
-- Name: app_users_groups_appuser_id_c013f67f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_users_groups_appuser_id_c013f67f ON public.app_users_groups USING btree (appuser_id);


--
-- Name: app_users_groups_group_id_b415af26; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_users_groups_group_id_b415af26 ON public.app_users_groups USING btree (group_id);


--
-- Name: app_users_user_permissions_appuser_id_51d472f7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_users_user_permissions_appuser_id_51d472f7 ON public.app_users_user_permissions USING btree (appuser_id);


--
-- Name: app_users_user_permissions_permission_id_2479a5e1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX app_users_user_permissions_permission_id_2479a5e1 ON public.app_users_user_permissions USING btree (permission_id);


--
-- Name: application_applica_962b71_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX application_applica_962b71_idx ON public.application_attachments USING btree (application_type);


--
-- Name: application_attachments_district_id_4512bac0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX application_attachments_district_id_4512bac0 ON public.application_attachments USING btree (district_id);


--
-- Name: application_attachments_public_entry_id_acee7110; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX application_attachments_public_entry_id_acee7110 ON public.application_attachments USING btree (public_entry_id);


--
-- Name: application_attachments_uploaded_by_id_9da00073; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX application_attachments_uploaded_by_id_9da00073 ON public.application_attachments USING btree (uploaded_by_id);


--
-- Name: application_distric_102562_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX application_distric_102562_idx ON public.application_attachments USING btree (district_id);


--
-- Name: application_institu_972890_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX application_institu_972890_idx ON public.application_attachments USING btree (institution_application_number);


--
-- Name: application_public__7b7f12_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX application_public__7b7f12_idx ON public.application_attachments USING btree (public_entry_id);


--
-- Name: articles_article_eb0d2c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX articles_article_eb0d2c_idx ON public.articles USING btree (article_name);


--
-- Name: articles_article_name_3843e89c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX articles_article_name_3843e89c_like ON public.articles USING btree (article_name varchar_pattern_ops);


--
-- Name: articles_categor_052161_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX articles_categor_052161_idx ON public.articles USING btree (category);


--
-- Name: articles_item_ty_7b4107_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX articles_item_ty_7b4107_idx ON public.articles USING btree (item_type, is_active);


--
-- Name: audit_logs_action__168beb_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_action__168beb_idx ON public.audit_logs USING btree (action_type);


--
-- Name: audit_logs_created_262184_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_created_262184_idx ON public.audit_logs USING btree (created_at);


--
-- Name: audit_logs_entity__4f758f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_entity__4f758f_idx ON public.audit_logs USING btree (entity_type);


--
-- Name: audit_logs_entity__d4c2e5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_entity__d4c2e5_idx ON public.audit_logs USING btree (entity_type, entity_id);


--
-- Name: audit_logs_user_id_73c422_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_user_id_73c422_idx ON public.audit_logs USING btree (user_id);


--
-- Name: audit_logs_user_id_752b0e2b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_user_id_752b0e2b ON public.audit_logs USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: dashboard_settings_updated_by_id_814f5cc0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dashboard_settings_updated_by_id_814f5cc0 ON public.dashboard_settings USING btree (updated_by_id);


--
-- Name: district_be_article_070957_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_be_article_070957_idx ON public.district_beneficiary_entries USING btree (article_id);


--
-- Name: district_be_distric_ba2ae8_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_be_distric_ba2ae8_idx ON public.district_beneficiary_entries USING btree (district_id);


--
-- Name: district_be_fund_re_25db26_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_be_fund_re_25db26_idx ON public.district_beneficiary_entries USING btree (fund_request_id);


--
-- Name: district_be_status_aa5eaf_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_be_status_aa5eaf_idx ON public.district_beneficiary_entries USING btree (status);


--
-- Name: district_beneficiary_entries_application_number_4ebbc113; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_beneficiary_entries_application_number_4ebbc113 ON public.district_beneficiary_entries USING btree (application_number);


--
-- Name: district_beneficiary_entries_application_number_4ebbc113_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_beneficiary_entries_application_number_4ebbc113_like ON public.district_beneficiary_entries USING btree (application_number varchar_pattern_ops);


--
-- Name: district_beneficiary_entries_article_id_6462b2e1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_beneficiary_entries_article_id_6462b2e1 ON public.district_beneficiary_entries USING btree (article_id);


--
-- Name: district_beneficiary_entries_created_by_id_22b42354; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_beneficiary_entries_created_by_id_22b42354 ON public.district_beneficiary_entries USING btree (created_by_id);


--
-- Name: district_beneficiary_entries_district_id_91a878b8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_beneficiary_entries_district_id_91a878b8 ON public.district_beneficiary_entries USING btree (district_id);


--
-- Name: district_beneficiary_entries_fund_request_id_8a3dfade; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_beneficiary_entries_fund_request_id_8a3dfade ON public.district_beneficiary_entries USING btree (fund_request_id);


--
-- Name: district_ma_distric_5f17d4_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_ma_distric_5f17d4_idx ON public.district_master USING btree (district_name);


--
-- Name: district_ma_is_acti_f4f03c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_ma_is_acti_f4f03c_idx ON public.district_master USING btree (is_active);


--
-- Name: district_master_district_name_2d41f9d1_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX district_master_district_name_2d41f9d1_like ON public.district_master USING btree (district_name varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: event_sessi_event_y_2e0fa6_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX event_sessi_event_y_2e0fa6_idx ON public.event_sessions USING btree (event_year);


--
-- Name: event_sessi_is_acti_ea8fbc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX event_sessi_is_acti_ea8fbc_idx ON public.event_sessions USING btree (is_active);


--
-- Name: event_sessions_session_name_e5fbd3e6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX event_sessions_session_name_e5fbd3e6_like ON public.event_sessions USING btree (session_name varchar_pattern_ops);


--
-- Name: fund_reques_article_f45367_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_article_f45367_idx ON public.fund_request_articles USING btree (article_id);


--
-- Name: fund_reques_benefic_2b0c27_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_benefic_2b0c27_idx ON public.fund_request_recipients USING btree (beneficiary_type, source_entry_id);


--
-- Name: fund_reques_benefic_3fee69_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_benefic_3fee69_idx ON public.fund_request_recipients USING btree (beneficiary_type);


--
-- Name: fund_reques_created_f8c661_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_created_f8c661_idx ON public.fund_request USING btree (created_at);


--
-- Name: fund_reques_fund_re_3f5709_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_fund_re_3f5709_idx ON public.fund_request USING btree (fund_request_number);


--
-- Name: fund_reques_fund_re_9dfd19_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_fund_re_9dfd19_idx ON public.fund_request_articles USING btree (fund_request_id);


--
-- Name: fund_reques_fund_re_ae1c10_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_fund_re_ae1c10_idx ON public.fund_request_recipients USING btree (fund_request_id);


--
-- Name: fund_reques_fund_re_e61cd8_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_fund_re_e61cd8_idx ON public.fund_request USING btree (fund_request_type);


--
-- Name: fund_reques_status_9abf3b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_status_9abf3b_idx ON public.fund_request USING btree (status);


--
-- Name: fund_reques_vendor__1e094a_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_reques_vendor__1e094a_idx ON public.fund_request_articles USING btree (vendor_id);


--
-- Name: fund_request_articles_article_id_4940c111; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_request_articles_article_id_4940c111 ON public.fund_request_articles USING btree (article_id);


--
-- Name: fund_request_articles_fund_request_id_b2eb3dd9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_request_articles_fund_request_id_b2eb3dd9 ON public.fund_request_articles USING btree (fund_request_id);


--
-- Name: fund_request_articles_vendor_id_6226a792; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_request_articles_vendor_id_6226a792 ON public.fund_request_articles USING btree (vendor_id);


--
-- Name: fund_request_created_by_id_7fd22ac7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_request_created_by_id_7fd22ac7 ON public.fund_request USING btree (created_by_id);


--
-- Name: fund_request_documents_fund_request_id_322f4f26; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_request_documents_fund_request_id_322f4f26 ON public.fund_request_documents USING btree (fund_request_id);


--
-- Name: fund_request_documents_generated_by_id_d0a1f8e5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_request_documents_generated_by_id_d0a1f8e5 ON public.fund_request_documents USING btree (generated_by_id);


--
-- Name: fund_request_fund_request_number_02b8dc8a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_request_fund_request_number_02b8dc8a_like ON public.fund_request USING btree (fund_request_number varchar_pattern_ops);


--
-- Name: fund_request_recipients_fund_request_id_95213969; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_request_recipients_fund_request_id_95213969 ON public.fund_request_recipients USING btree (fund_request_id);


--
-- Name: institution_applica_8f5588_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX institution_applica_8f5588_idx ON public.institutions_beneficiary_entries USING btree (application_number);


--
-- Name: institution_article_d7a6b7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX institution_article_d7a6b7_idx ON public.institutions_beneficiary_entries USING btree (article_id);


--
-- Name: institution_fund_re_ea2f5b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX institution_fund_re_ea2f5b_idx ON public.institutions_beneficiary_entries USING btree (fund_request_id);


--
-- Name: institution_institu_30e104_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX institution_institu_30e104_idx ON public.institutions_beneficiary_entries USING btree (institution_type);


--
-- Name: institution_status_c32d33_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX institution_status_c32d33_idx ON public.institutions_beneficiary_entries USING btree (status);


--
-- Name: institutions_beneficiary_entries_article_id_e549cb19; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX institutions_beneficiary_entries_article_id_e549cb19 ON public.institutions_beneficiary_entries USING btree (article_id);


--
-- Name: institutions_beneficiary_entries_created_by_id_735bd552; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX institutions_beneficiary_entries_created_by_id_735bd552 ON public.institutions_beneficiary_entries USING btree (created_by_id);


--
-- Name: institutions_beneficiary_entries_fund_request_id_496bbd5a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX institutions_beneficiary_entries_fund_request_id_496bbd5a ON public.institutions_beneficiary_entries USING btree (fund_request_id);


--
-- Name: label_gener_session_item_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX label_gener_session_item_idx ON public.label_generation_rows USING btree (session_id, requested_item);


--
-- Name: label_gener_session_seq_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX label_gener_session_seq_idx ON public.label_generation_rows USING btree (session_id, sequence_no);


--
-- Name: label_gener_session_sort_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX label_gener_session_sort_idx ON public.label_generation_rows USING btree (session_id, sort_order);


--
-- Name: label_generation_rows_created_by_id_a79bbcf6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX label_generation_rows_created_by_id_a79bbcf6 ON public.label_generation_rows USING btree (created_by_id);


--
-- Name: label_generation_rows_session_id_93ee3b9e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX label_generation_rows_session_id_93ee3b9e ON public.label_generation_rows USING btree (session_id);


--
-- Name: label_generation_rows_updated_by_id_6656d27a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX label_generation_rows_updated_by_id_6656d27a ON public.label_generation_rows USING btree (updated_by_id);


--
-- Name: order_entri_article_4c6a70_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX order_entri_article_4c6a70_idx ON public.order_entries USING btree (article_id, status);


--
-- Name: order_entri_article_6b0079_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX order_entri_article_6b0079_idx ON public.order_entries USING btree (article_id);


--
-- Name: order_entri_fund_re_958bf0_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX order_entri_fund_re_958bf0_idx ON public.order_entries USING btree (fund_request_id);


--
-- Name: order_entri_order_d_a1ac8e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX order_entri_order_d_a1ac8e_idx ON public.order_entries USING btree (order_date);


--
-- Name: order_entri_status_1c1620_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX order_entri_status_1c1620_idx ON public.order_entries USING btree (status);


--
-- Name: order_entries_article_id_27194aea; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX order_entries_article_id_27194aea ON public.order_entries USING btree (article_id);


--
-- Name: order_entries_created_by_id_1f80860c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX order_entries_created_by_id_1f80860c ON public.order_entries USING btree (created_by_id);


--
-- Name: order_entries_fund_request_id_143a2d52; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX order_entries_fund_request_id_143a2d52 ON public.order_entries USING btree (fund_request_id);


--
-- Name: public_bene_aadhar__1636ab_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_bene_aadhar__1636ab_idx ON public.public_beneficiary_entries USING btree (aadhar_number);


--
-- Name: public_bene_applica_2b6bf7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_bene_applica_2b6bf7_idx ON public.public_beneficiary_entries USING btree (application_number);


--
-- Name: public_bene_article_1b0642_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_bene_article_1b0642_idx ON public.public_beneficiary_entries USING btree (article_id);


--
-- Name: public_bene_female__e9ca16_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_bene_female__e9ca16_idx ON public.public_beneficiary_entries USING btree (female_status);


--
-- Name: public_bene_fund_re_559f4c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_bene_fund_re_559f4c_idx ON public.public_beneficiary_entries USING btree (fund_request_id);


--
-- Name: public_bene_gender_49003f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_bene_gender_49003f_idx ON public.public_beneficiary_entries USING btree (gender);


--
-- Name: public_bene_status_fd01f2_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_bene_status_fd01f2_idx ON public.public_beneficiary_entries USING btree (status);


--
-- Name: public_beneficiary_entries_application_number_99b638ca_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_beneficiary_entries_application_number_99b638ca_like ON public.public_beneficiary_entries USING btree (application_number varchar_pattern_ops);


--
-- Name: public_beneficiary_entries_article_id_295fdd50; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_beneficiary_entries_article_id_295fdd50 ON public.public_beneficiary_entries USING btree (article_id);


--
-- Name: public_beneficiary_entries_created_by_id_545322c8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_beneficiary_entries_created_by_id_545322c8 ON public.public_beneficiary_entries USING btree (created_by_id);


--
-- Name: public_beneficiary_entries_fund_request_id_3145efe5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX public_beneficiary_entries_fund_request_id_3145efe5 ON public.public_beneficiary_entries USING btree (fund_request_id);


--
-- Name: purchase_or_article_59dca9_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_or_article_59dca9_idx ON public.purchase_order_items USING btree (article_id);


--
-- Name: purchase_or_created_a0c5eb_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_or_created_a0c5eb_idx ON public.purchase_order USING btree (created_at);


--
-- Name: purchase_or_purchas_49b03b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_or_purchas_49b03b_idx ON public.purchase_order USING btree (purchase_order_number);


--
-- Name: purchase_or_purchas_a61376_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_or_purchas_a61376_idx ON public.purchase_order_items USING btree (purchase_order_id);


--
-- Name: purchase_or_status_86ae3f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_or_status_86ae3f_idx ON public.purchase_order USING btree (status);


--
-- Name: purchase_order_created_by_id_112332e4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_order_created_by_id_112332e4 ON public.purchase_order USING btree (created_by_id);


--
-- Name: purchase_order_items_article_id_2294fd65; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_order_items_article_id_2294fd65 ON public.purchase_order_items USING btree (article_id);


--
-- Name: purchase_order_items_purchase_order_id_0c2f986f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_order_items_purchase_order_id_0c2f986f ON public.purchase_order_items USING btree (purchase_order_id);


--
-- Name: purchase_order_purchase_order_number_d7a32ce4_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_order_purchase_order_number_d7a32ce4_like ON public.purchase_order USING btree (purchase_order_number varchar_pattern_ops);


--
-- Name: seat_alloca_session_2f4f36_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX seat_alloca_session_2f4f36_idx ON public.seat_allocation_rows USING btree (session_id, requested_item);


--
-- Name: seat_alloca_session_a45f13_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX seat_alloca_session_a45f13_idx ON public.seat_allocation_rows USING btree (session_id, sort_order);


--
-- Name: seat_alloca_session_b6ac3b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX seat_alloca_session_b6ac3b_idx ON public.seat_allocation_rows USING btree (session_id, sequence_no);


--
-- Name: seat_alloca_session_d477f8_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX seat_alloca_session_d477f8_idx ON public.seat_allocation_rows USING btree (session_id, beneficiary_type);


--
-- Name: seat_allocation_rows_created_by_id_42d7df80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX seat_allocation_rows_created_by_id_42d7df80 ON public.seat_allocation_rows USING btree (created_by_id);


--
-- Name: seat_allocation_rows_session_id_a51bd2cf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX seat_allocation_rows_session_id_a51bd2cf ON public.seat_allocation_rows USING btree (session_id);


--
-- Name: seat_allocation_rows_updated_by_id_f569fe0d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX seat_allocation_rows_updated_by_id_f569fe0d ON public.seat_allocation_rows USING btree (updated_by_id);


--
-- Name: sequence_li_session_68ddc8_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sequence_li_session_68ddc8_idx ON public.sequence_list_items USING btree (session_id, sequence_no);


--
-- Name: sequence_li_session_8f80d2_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sequence_li_session_8f80d2_idx ON public.sequence_list_items USING btree (session_id, sort_order);


--
-- Name: sequence_list_items_created_by_id_3aff8b57; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sequence_list_items_created_by_id_3aff8b57 ON public.sequence_list_items USING btree (created_by_id);


--
-- Name: sequence_list_items_session_id_a9729ca2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sequence_list_items_session_id_a9729ca2 ON public.sequence_list_items USING btree (session_id);


--
-- Name: sequence_list_items_updated_by_id_fca242d8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sequence_list_items_updated_by_id_fca242d8 ON public.sequence_list_items USING btree (updated_by_id);


--
-- Name: token_gener_sessio_0cb65f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_gener_sessio_0cb65f_idx ON public.token_generation_rows USING btree (session_id, requested_item);


--
-- Name: token_gener_sessio_0d77fd_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_gener_sessio_0d77fd_idx ON public.token_generation_rows USING btree (session_id, sort_order);


--
-- Name: token_gener_sessio_59c8c9_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_gener_sessio_59c8c9_idx ON public.token_generation_rows USING btree (session_id, sequence_no);


--
-- Name: token_generation_rows_created_by_id_a7e4563f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_generation_rows_created_by_id_a7e4563f ON public.token_generation_rows USING btree (created_by_id);


--
-- Name: token_generation_rows_session_id_2a6c97c7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_generation_rows_session_id_2a6c97c7 ON public.token_generation_rows USING btree (session_id);


--
-- Name: token_generation_rows_updated_by_id_898404dd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_generation_rows_updated_by_id_898404dd ON public.token_generation_rows USING btree (updated_by_id);


--
-- Name: uniq_fund_request_recipient_source_global; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_fund_request_recipient_source_global ON public.fund_request_recipients USING btree (beneficiary_type, source_entry_id) WHERE (source_entry_id IS NOT NULL);


--
-- Name: user_module_permissions_user_id_0b8b1532; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_module_permissions_user_id_0b8b1532 ON public.user_module_permissions USING btree (user_id);


--
-- Name: vendors_gst_num_3dba9e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vendors_gst_num_3dba9e_idx ON public.vendors USING btree (gst_number);


--
-- Name: vendors_is_acti_04b085_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vendors_is_acti_04b085_idx ON public.vendors USING btree (is_active);


--
-- Name: vendors_vendor__4ce451_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vendors_vendor__4ce451_idx ON public.vendors USING btree (vendor_name);


--
-- Name: app_users app_users_created_by_id_b75edff3_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_created_by_id_b75edff3_fk_app_users_id FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_users_groups app_users_groups_appuser_id_c013f67f_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users_groups
    ADD CONSTRAINT app_users_groups_appuser_id_c013f67f_fk_app_users_id FOREIGN KEY (appuser_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_users_groups app_users_groups_group_id_b415af26_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users_groups
    ADD CONSTRAINT app_users_groups_group_id_b415af26_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_users_user_permissions app_users_user_permi_permission_id_2479a5e1_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users_user_permissions
    ADD CONSTRAINT app_users_user_permi_permission_id_2479a5e1_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_users_user_permissions app_users_user_permissions_appuser_id_51d472f7_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users_user_permissions
    ADD CONSTRAINT app_users_user_permissions_appuser_id_51d472f7_fk_app_users_id FOREIGN KEY (appuser_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: application_attachments application_attachme_district_id_4512bac0_fk_district_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_attachments
    ADD CONSTRAINT application_attachme_district_id_4512bac0_fk_district_ FOREIGN KEY (district_id) REFERENCES public.district_master(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: application_attachments application_attachme_public_entry_id_acee7110_fk_public_be; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_attachments
    ADD CONSTRAINT application_attachme_public_entry_id_acee7110_fk_public_be FOREIGN KEY (public_entry_id) REFERENCES public.public_beneficiary_entries(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: application_attachments application_attachments_uploaded_by_id_9da00073_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_attachments
    ADD CONSTRAINT application_attachments_uploaded_by_id_9da00073_fk_app_users_id FOREIGN KEY (uploaded_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: audit_logs audit_logs_user_id_752b0e2b_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_752b0e2b_fk_app_users_id FOREIGN KEY (user_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dashboard_settings dashboard_settings_updated_by_id_814f5cc0_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dashboard_settings
    ADD CONSTRAINT dashboard_settings_updated_by_id_814f5cc0_fk_app_users_id FOREIGN KEY (updated_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: district_beneficiary_entries district_beneficiary_created_by_id_22b42354_fk_app_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district_beneficiary_entries
    ADD CONSTRAINT district_beneficiary_created_by_id_22b42354_fk_app_users FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: district_beneficiary_entries district_beneficiary_district_id_91a878b8_fk_district_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district_beneficiary_entries
    ADD CONSTRAINT district_beneficiary_district_id_91a878b8_fk_district_ FOREIGN KEY (district_id) REFERENCES public.district_master(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: district_beneficiary_entries district_beneficiary_entries_article_id_6462b2e1_fk_articles_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district_beneficiary_entries
    ADD CONSTRAINT district_beneficiary_entries_article_id_6462b2e1_fk_articles_id FOREIGN KEY (article_id) REFERENCES public.articles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: district_beneficiary_entries district_beneficiary_fund_request_id_8a3dfade_fk_fund_requ; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district_beneficiary_entries
    ADD CONSTRAINT district_beneficiary_fund_request_id_8a3dfade_fk_fund_requ FOREIGN KEY (fund_request_id) REFERENCES public.fund_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_app_users_id FOREIGN KEY (user_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fund_request_articles fund_request_article_fund_request_id_b2eb3dd9_fk_fund_requ; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request_articles
    ADD CONSTRAINT fund_request_article_fund_request_id_b2eb3dd9_fk_fund_requ FOREIGN KEY (fund_request_id) REFERENCES public.fund_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fund_request_articles fund_request_articles_article_id_4940c111_fk_articles_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request_articles
    ADD CONSTRAINT fund_request_articles_article_id_4940c111_fk_articles_id FOREIGN KEY (article_id) REFERENCES public.articles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fund_request_articles fund_request_articles_vendor_id_6226a792_fk_vendors_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request_articles
    ADD CONSTRAINT fund_request_articles_vendor_id_6226a792_fk_vendors_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fund_request fund_request_created_by_id_7fd22ac7_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request
    ADD CONSTRAINT fund_request_created_by_id_7fd22ac7_fk_app_users_id FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fund_request_documents fund_request_documen_fund_request_id_322f4f26_fk_fund_requ; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request_documents
    ADD CONSTRAINT fund_request_documen_fund_request_id_322f4f26_fk_fund_requ FOREIGN KEY (fund_request_id) REFERENCES public.fund_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fund_request_documents fund_request_documents_generated_by_id_d0a1f8e5_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request_documents
    ADD CONSTRAINT fund_request_documents_generated_by_id_d0a1f8e5_fk_app_users_id FOREIGN KEY (generated_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fund_request_recipients fund_request_recipie_fund_request_id_95213969_fk_fund_requ; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_request_recipients
    ADD CONSTRAINT fund_request_recipie_fund_request_id_95213969_fk_fund_requ FOREIGN KEY (fund_request_id) REFERENCES public.fund_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: institutions_beneficiary_entries institutions_benefic_article_id_e549cb19_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.institutions_beneficiary_entries
    ADD CONSTRAINT institutions_benefic_article_id_e549cb19_fk_articles_ FOREIGN KEY (article_id) REFERENCES public.articles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: institutions_beneficiary_entries institutions_benefic_created_by_id_735bd552_fk_app_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.institutions_beneficiary_entries
    ADD CONSTRAINT institutions_benefic_created_by_id_735bd552_fk_app_users FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: institutions_beneficiary_entries institutions_benefic_fund_request_id_496bbd5a_fk_fund_requ; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.institutions_beneficiary_entries
    ADD CONSTRAINT institutions_benefic_fund_request_id_496bbd5a_fk_fund_requ FOREIGN KEY (fund_request_id) REFERENCES public.fund_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: label_generation_rows label_generation_rows_created_by_id_a79bbcf6_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.label_generation_rows
    ADD CONSTRAINT label_generation_rows_created_by_id_a79bbcf6_fk_app_users_id FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: label_generation_rows label_generation_rows_session_id_93ee3b9e_fk_event_sessions_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.label_generation_rows
    ADD CONSTRAINT label_generation_rows_session_id_93ee3b9e_fk_event_sessions_id FOREIGN KEY (session_id) REFERENCES public.event_sessions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: label_generation_rows label_generation_rows_updated_by_id_6656d27a_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.label_generation_rows
    ADD CONSTRAINT label_generation_rows_updated_by_id_6656d27a_fk_app_users_id FOREIGN KEY (updated_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_entries order_entries_article_id_27194aea_fk_articles_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_entries
    ADD CONSTRAINT order_entries_article_id_27194aea_fk_articles_id FOREIGN KEY (article_id) REFERENCES public.articles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_entries order_entries_created_by_id_1f80860c_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_entries
    ADD CONSTRAINT order_entries_created_by_id_1f80860c_fk_app_users_id FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_entries order_entries_fund_request_id_143a2d52_fk_fund_request_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_entries
    ADD CONSTRAINT order_entries_fund_request_id_143a2d52_fk_fund_request_id FOREIGN KEY (fund_request_id) REFERENCES public.fund_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: public_beneficiary_entries public_beneficiary_e_created_by_id_545322c8_fk_app_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_beneficiary_entries
    ADD CONSTRAINT public_beneficiary_e_created_by_id_545322c8_fk_app_users FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: public_beneficiary_entries public_beneficiary_e_fund_request_id_3145efe5_fk_fund_requ; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_beneficiary_entries
    ADD CONSTRAINT public_beneficiary_e_fund_request_id_3145efe5_fk_fund_requ FOREIGN KEY (fund_request_id) REFERENCES public.fund_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: public_beneficiary_entries public_beneficiary_entries_article_id_295fdd50_fk_articles_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_beneficiary_entries
    ADD CONSTRAINT public_beneficiary_entries_article_id_295fdd50_fk_articles_id FOREIGN KEY (article_id) REFERENCES public.articles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: purchase_order purchase_order_created_by_id_112332e4_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_order
    ADD CONSTRAINT purchase_order_created_by_id_112332e4_fk_app_users_id FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: purchase_order_items purchase_order_items_article_id_2294fd65_fk_articles_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_order_items
    ADD CONSTRAINT purchase_order_items_article_id_2294fd65_fk_articles_id FOREIGN KEY (article_id) REFERENCES public.articles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: purchase_order_items purchase_order_items_purchase_order_id_0c2f986f_fk_purchase_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_order_items
    ADD CONSTRAINT purchase_order_items_purchase_order_id_0c2f986f_fk_purchase_ FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: seat_allocation_rows seat_allocation_rows_created_by_id_42d7df80_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seat_allocation_rows
    ADD CONSTRAINT seat_allocation_rows_created_by_id_42d7df80_fk_app_users_id FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: seat_allocation_rows seat_allocation_rows_session_id_a51bd2cf_fk_event_sessions_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seat_allocation_rows
    ADD CONSTRAINT seat_allocation_rows_session_id_a51bd2cf_fk_event_sessions_id FOREIGN KEY (session_id) REFERENCES public.event_sessions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: seat_allocation_rows seat_allocation_rows_updated_by_id_f569fe0d_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seat_allocation_rows
    ADD CONSTRAINT seat_allocation_rows_updated_by_id_f569fe0d_fk_app_users_id FOREIGN KEY (updated_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sequence_list_items sequence_list_items_created_by_id_3aff8b57_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_list_items
    ADD CONSTRAINT sequence_list_items_created_by_id_3aff8b57_fk_app_users_id FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sequence_list_items sequence_list_items_session_id_a9729ca2_fk_event_sessions_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_list_items
    ADD CONSTRAINT sequence_list_items_session_id_a9729ca2_fk_event_sessions_id FOREIGN KEY (session_id) REFERENCES public.event_sessions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sequence_list_items sequence_list_items_updated_by_id_fca242d8_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_list_items
    ADD CONSTRAINT sequence_list_items_updated_by_id_fca242d8_fk_app_users_id FOREIGN KEY (updated_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_generation_rows token_generation_rows_created_by_id_a7e4563f_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_generation_rows
    ADD CONSTRAINT token_generation_rows_created_by_id_a7e4563f_fk_app_users_id FOREIGN KEY (created_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_generation_rows token_generation_rows_session_id_2a6c97c7_fk_event_sessions_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_generation_rows
    ADD CONSTRAINT token_generation_rows_session_id_2a6c97c7_fk_event_sessions_id FOREIGN KEY (session_id) REFERENCES public.event_sessions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_generation_rows token_generation_rows_updated_by_id_898404dd_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_generation_rows
    ADD CONSTRAINT token_generation_rows_updated_by_id_898404dd_fk_app_users_id FOREIGN KEY (updated_by_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_module_permissions user_module_permissions_user_id_0b8b1532_fk_app_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_module_permissions
    ADD CONSTRAINT user_module_permissions_user_id_0b8b1532_fk_app_users_id FOREIGN KEY (user_id) REFERENCES public.app_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


