# Generated by Django 4.2.29 on 2026-03-17 08:40

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=9)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App User',
                'verbose_name_plural': 'App Users',
                'db_table': 'app_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_name', models.CharField(max_length=255, unique=True)),
                ('article_name_tk', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item_type', models.CharField(choices=[('Article', 'Article'), ('Aid', 'Aid'), ('Project', 'Project')], default='Article', max_length=20)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('master_category', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('combo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_request_type', models.CharField(choices=[('Aid', 'Aid'), ('Article', 'Article')], max_length=20)),
                ('fund_request_number', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('aid_type', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=64, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_address', models.TextField(blank=True, null=True)),
                ('supplier_city', models.CharField(blank=True, max_length=120, null=True)),
                ('supplier_state', models.CharField(blank=True, max_length=120, null=True)),
                ('supplier_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=80, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund Request',
                'verbose_name_plural': 'Fund Requests',
                'db_table': 'fund_request',
            },
        ),
        migrations.CreateModel(
            name='PublicBeneficiaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('article_name', models.CharField(blank=True, max_length=255, null=True)),
                ('application_number', models.CharField(blank=True, max_length=120, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_handicapped', models.BooleanField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_number_sp', models.CharField(blank=True, max_length=20, null=True)),
                ('is_selected', models.BooleanField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Public Beneficiary History',
                'verbose_name_plural': 'Public Beneficiary History',
                'db_table': 'public_beneficiary_history',
            },
        ),
        migrations.CreateModel(
            name='PublicBeneficiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('aadhar_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(12)])),
                ('is_handicapped', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=15, null=True)),
                ('female_status', models.CharField(blank=True, choices=[('Single Mother', 'Single Mother'), ('Widow', 'Widow'), ('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('article_cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='public_entries', to='core.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_entries', to=settings.AUTH_USER_MODEL)),
                ('fund_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_public_beneficiaries', to='core.fundrequest')),
            ],
            options={
                'verbose_name': 'Public Beneficiary Entry',
                'verbose_name_plural': 'Public Beneficiary Entries',
                'db_table': 'public_beneficiary_entries',
            },
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_ordered', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='core.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('fund_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_entries', to='core.fundrequest')),
            ],
            options={
                'verbose_name': 'Order Entry',
                'verbose_name_plural': 'Order Entries',
                'db_table': 'order_entries',
            },
        ),
        migrations.CreateModel(
            name='InstitutionsBeneficiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('institutions', 'Institutions'), ('others', 'Others')], max_length=20)),
                ('application_number', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('article_cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='institution_entries', to='core.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_institution_entries', to=settings.AUTH_USER_MODEL)),
                ('fund_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_institution_beneficiaries', to='core.fundrequest')),
            ],
            options={
                'verbose_name': 'Institutions / Others Beneficiary Entry',
                'verbose_name_plural': 'Institutions / Others Beneficiary Entries',
                'db_table': 'institutions_beneficiary_entries',
            },
        ),
        migrations.CreateModel(
            name='FundRequestRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_type', models.CharField(blank=True, choices=[('District', 'District'), ('Public', 'Public'), ('Institutions', 'Institutions'), ('Others', 'Others')], max_length=20, null=True)),
                ('beneficiary', models.TextField(blank=True, null=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('name_of_beneficiary', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('fund_requested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('cheque_in_favour', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.fundrequest')),
            ],
            options={
                'verbose_name': 'Fund Request Recipient',
                'verbose_name_plural': 'Fund Request Recipients',
                'db_table': 'fund_request_recipients',
            },
        ),
        migrations.CreateModel(
            name='FundRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('fund_request', 'Fund Request'), ('purchase_order', 'Purchase Order')], max_length=20)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.fundrequest')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund Request Document',
                'verbose_name_plural': 'Fund Request Documents',
                'db_table': 'fund_request_documents',
            },
        ),
        migrations.CreateModel(
            name='FundRequestArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sl_no', models.PositiveIntegerField(blank=True, null=True)),
                ('beneficiary', models.TextField(blank=True, null=True)),
                ('article_name', models.CharField(max_length=255)),
                ('gst_no', models.CharField(blank=True, max_length=64, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price_including_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cumulative', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cheque_in_favour', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=120, null=True)),
                ('supplier_article_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fund_request_lines', to='core.article')),
                ('fund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.fundrequest')),
            ],
            options={
                'verbose_name': 'Fund Request Article',
                'verbose_name_plural': 'Fund Request Articles',
                'db_table': 'fund_request_articles',
            },
        ),
        migrations.CreateModel(
            name='DistrictMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_name', models.CharField(max_length=255, unique=True)),
                ('allotted_budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('president_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('application_number', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'district_master',
                'indexes': [models.Index(fields=['district_name'], name='district_ma_distric_5f17d4_idx'), models.Index(fields=['is_active'], name='district_ma_is_acti_f4f03c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DistrictBeneficiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('article_cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='district_entries', to='core.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_district_entries', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='beneficiaries', to='core.districtmaster')),
                ('fund_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_district_beneficiaries', to='core.fundrequest')),
            ],
            options={
                'verbose_name': 'District Beneficiary Entry',
                'verbose_name_plural': 'District Beneficiary Entries',
                'db_table': 'district_beneficiary_entries',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('STATUS_CHANGE', 'Status Change')], max_length=16)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=120, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_name'], name='articles_article_eb0d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['item_type', 'is_active'], name='articles_item_ty_7b4107_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='articles_categor_052161_idx'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='publicbeneficiaryentry',
            index=models.Index(fields=['status'], name='public_bene_status_fd01f2_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbeneficiaryentry',
            index=models.Index(fields=['article'], name='public_bene_article_1b0642_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbeneficiaryentry',
            index=models.Index(fields=['aadhar_number'], name='public_bene_aadhar__1636ab_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbeneficiaryentry',
            index=models.Index(fields=['application_number'], name='public_bene_applica_2b6bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbeneficiaryentry',
            index=models.Index(fields=['fund_request'], name='public_bene_fund_re_559f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbeneficiaryentry',
            index=models.Index(fields=['gender'], name='public_bene_gender_49003f_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbeneficiaryentry',
            index=models.Index(fields=['female_status'], name='public_bene_female__e9ca16_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['article'], name='order_entri_article_6b0079_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['status'], name='order_entri_status_1c1620_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['order_date'], name='order_entri_order_d_a1ac8e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['article', 'status'], name='order_entri_article_4c6a70_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['fund_request'], name='order_entri_fund_re_958bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionsbeneficiaryentry',
            index=models.Index(fields=['institution_type'], name='institution_institu_30e104_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionsbeneficiaryentry',
            index=models.Index(fields=['application_number'], name='institution_applica_8f5588_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionsbeneficiaryentry',
            index=models.Index(fields=['status'], name='institution_status_c32d33_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionsbeneficiaryentry',
            index=models.Index(fields=['fund_request'], name='institution_fund_re_ea2f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionsbeneficiaryentry',
            index=models.Index(fields=['article'], name='institution_article_d7a6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='fundrequestrecipient',
            index=models.Index(fields=['fund_request'], name='fund_reques_fund_re_ae1c10_idx'),
        ),
        migrations.AddIndex(
            model_name='fundrequestrecipient',
            index=models.Index(fields=['beneficiary_type'], name='fund_reques_benefic_3fee69_idx'),
        ),
        migrations.AddIndex(
            model_name='fundrequestarticle',
            index=models.Index(fields=['fund_request'], name='fund_reques_fund_re_9dfd19_idx'),
        ),
        migrations.AddIndex(
            model_name='fundrequestarticle',
            index=models.Index(fields=['article'], name='fund_reques_article_f45367_idx'),
        ),
        migrations.AddIndex(
            model_name='fundrequest',
            index=models.Index(fields=['fund_request_type'], name='fund_reques_fund_re_e61cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='fundrequest',
            index=models.Index(fields=['status'], name='fund_reques_status_9abf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='fundrequest',
            index=models.Index(fields=['fund_request_number'], name='fund_reques_fund_re_3f5709_idx'),
        ),
        migrations.AddIndex(
            model_name='fundrequest',
            index=models.Index(fields=['created_at'], name='fund_reques_created_f8c661_idx'),
        ),
        migrations.AddIndex(
            model_name='districtbeneficiaryentry',
            index=models.Index(fields=['district'], name='district_be_distric_ba2ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='districtbeneficiaryentry',
            index=models.Index(fields=['article'], name='district_be_article_070957_idx'),
        ),
        migrations.AddIndex(
            model_name='districtbeneficiaryentry',
            index=models.Index(fields=['status'], name='district_be_status_aa5eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='districtbeneficiaryentry',
            index=models.Index(fields=['fund_request'], name='district_be_fund_re_25db26_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type'], name='audit_logs_action__168beb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type'], name='audit_logs_entity__4f758f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'),
        ),
    ]
