# Generated by Django 4.2.29 on 2026-03-19 10:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', core.models.AppUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='publicbeneficiaryentry',
            name='female_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Deserted', 'Deserted'), ('Single Mother', 'Single Mother'), ('Destitute Woman (no income/support)', 'Destitute Woman (no income/support)'), ('Female Head of Household', 'Female Head of Household'), ('Victim of Domestic Violence', 'Victim of Domestic Violence'), ('Survivor of Abuse', 'Survivor of Abuse'), ('Elderly Woman (60+)', 'Elderly Woman (60+)'), ('Homeless', 'Homeless'), ('Orphan / No Family Support', 'Orphan / No Family Support'), ('Migrant Woman', 'Migrant Woman'), ('Caregiver (children / elderly / disabled)', 'Caregiver (children / elderly / disabled)'), ('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student')], max_length=80, null=True),
        ),
    ]
