# Generated by Django 4.2.29 on 2026-03-20 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_districtbeneficiaryentry_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_type', models.CharField(choices=[('district', 'District'), ('public', 'Public'), ('institution', 'Institution')], max_length=20)),
                ('institution_application_number', models.CharField(blank=True, max_length=120, null=True)),
                ('file', models.FileField(upload_to='application_attachments/%Y/%m/%d')),
                ('file_name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_attachments', to='core.districtmaster')),
                ('public_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_attachments', to='core.publicbeneficiaryentry')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Attachment',
                'verbose_name_plural': 'Application Attachments',
                'db_table': 'application_attachments',
                'indexes': [models.Index(fields=['application_type'], name='application_applica_962b71_idx'), models.Index(fields=['district'], name='application_distric_102562_idx'), models.Index(fields=['public_entry'], name='application_public__7b7f12_idx'), models.Index(fields=['institution_application_number'], name='application_institu_972890_idx')],
            },
        ),
    ]
