# Generated by Django 4.2.29 on 2026-03-23 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
