# Generated by Django 4.2.29 on 2026-03-23 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appuser_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_key', models.CharField(choices=[('application_entry', 'Application Entry'), ('article_management', 'Article Management'), ('base_files', 'Base Files'), ('inventory_planning', 'Inventory Planning'), ('order_fund_request', 'Order & Fund Request'), ('audit_logs', 'Audit Logs'), ('user_management', 'User Management')], max_length=64)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_submit', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_upload_replace', models.BooleanField(default=False)),
                ('can_reset_password', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Module Permission',
                'verbose_name_plural': 'User Module Permissions',
                'db_table': 'user_module_permissions',
                'ordering': ['module_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='usermodulepermission',
            constraint=models.UniqueConstraint(fields=('user', 'module_key'), name='unique_user_module_permission'),
        ),
    ]
