# Generated by Django 4.2.29 on 2026-03-23 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usermodulepermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dashboard_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Setting',
                'verbose_name_plural': 'Dashboard Settings',
                'db_table': 'dashboard_settings',
            },
        ),
    ]
