# Generated by Django 4.2.29 on 2026-03-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dashboardsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbeneficiaryentry',
            name='disability_category',
            field=models.CharField(blank=True, choices=[('Blindness / Low Vision', 'Blindness / Low Vision'), ('Deaf / Hard of Hearing', 'Deaf / Hard of Hearing'), ('Locomotor Disability', 'Locomotor Disability'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Leprosy Cured', 'Leprosy Cured'), ('Dwarfism', 'Dwarfism'), ('Acid Attack Victim', 'Acid Attack Victim'), ('Muscular Dystrophy', 'Muscular Dystrophy'), ('Autism Spectrum Disorder', 'Autism Spectrum Disorder'), ('Intellectual Disability', 'Intellectual Disability'), ('Specific Learning Disability', 'Specific Learning Disability'), ('Mental Illness', 'Mental Illness'), ('Multiple Disability', 'Multiple Disability'), ('Deaf-Blindness', 'Deaf-Blindness'), ('Other', 'Other')], max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='publicbeneficiaryentry',
            index=models.Index(fields=['disability_category'], name='public_bene_disabil_6d5509_idx'),
        ),
    ]
