# Generated by Django 4.2.29 on 2026-03-23 09:39

from django.db import migrations, models


def copy_handicapped_category_into_existing_field(apps, schema_editor):
    PublicBeneficiaryEntry = apps.get_model("core", "PublicBeneficiaryEntry")
    for entry in PublicBeneficiaryEntry.objects.all().only("id", "is_handicapped", "disability_category"):
        disability_category = (getattr(entry, "disability_category", None) or "").strip()
        raw_value = str(entry.is_handicapped).strip().lower()
        if disability_category:
            stored_value = disability_category
        elif raw_value in {"1", "true", "yes"}:
            stored_value = "Other"
        else:
            stored_value = "No"
        entry.is_handicapped = stored_value
        entry.save(update_fields=["is_handicapped"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_publicbeneficiaryentry_disability_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicbeneficiaryentry",
            name="is_handicapped",
            field=models.CharField(
                choices=[
                    ("No", "No"),
                    ("Blindness / Low Vision", "Blindness / Low Vision"),
                    ("Deaf / Hard of Hearing", "Deaf / Hard of Hearing"),
                    ("Locomotor Disability", "Locomotor Disability"),
                    ("Cerebral Palsy", "Cerebral Palsy"),
                    ("Leprosy Cured", "Leprosy Cured"),
                    ("Dwarfism", "Dwarfism"),
                    ("Acid Attack Victim", "Acid Attack Victim"),
                    ("Muscular Dystrophy", "Muscular Dystrophy"),
                    ("Autism Spectrum Disorder", "Autism Spectrum Disorder"),
                    ("Intellectual Disability", "Intellectual Disability"),
                    ("Specific Learning Disability", "Specific Learning Disability"),
                    ("Mental Illness", "Mental Illness"),
                    ("Multiple Disability", "Multiple Disability"),
                    ("Deaf-Blindness", "Deaf-Blindness"),
                    ("Other", "Other"),
                ],
                default="No",
                max_length=80,
            ),
        ),
        migrations.RunPython(copy_handicapped_category_into_existing_field, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="publicbeneficiaryentry",
            name="public_bene_disabil_6d5509_idx",
        ),
        migrations.RemoveField(
            model_name="publicbeneficiaryentry",
            name="disability_category",
        ),
    ]
