# Generated by Django 4.2.29 on 2026-03-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_publicbeneficiaryentry_public_bene_disabil_6d5509_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtbeneficiaryentry',
            name='cheque_rtgs_in_favour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutionsbeneficiaryentry',
            name='cheque_rtgs_in_favour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicbeneficiaryentry',
            name='cheque_rtgs_in_favour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
