# Generated by Django 4.2.29 on 2026-03-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_application_internal_notes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fundrequestarticle',
            new_name='fund_reques_vendor__1e094a_idx',
            old_name='fundreq_article_vendor_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_vendor__4ce451_idx',
            old_name='vendor_name_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_gst_num_3dba9e_idx',
            old_name='vendor_gst_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_is_acti_04b085_idx',
            old_name='vendor_active_idx',
        ),
    ]
