# Generated by Django 4.2.29 on 2026-04-18 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_vendor_phone_number'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='labelgenerationrow',
            new_name='label_gener_session_443b32_idx',
            old_name='label_gener_session_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='labelgenerationrow',
            new_name='label_gener_session_731f70_idx',
            old_name='label_gener_session_seq_idx',
        ),
        migrations.RenameIndex(
            model_name='labelgenerationrow',
            new_name='label_gener_session_0da4a7_idx',
            old_name='label_gener_session_item_idx',
        ),
        migrations.RenameIndex(
            model_name='sequencelistitem',
            new_name='sequence_li_session_b9393d_idx',
            old_name='sequence_li_session_68ddc8_idx',
        ),
        migrations.RenameIndex(
            model_name='sequencelistitem',
            new_name='sequence_li_session_7ee2fc_idx',
            old_name='sequence_li_session_8f80d2_idx',
        ),
        migrations.RenameIndex(
            model_name='tokengenerationrow',
            new_name='token_gener_session_ac62d3_idx',
            old_name='token_gener_sessio_0d77fd_idx',
        ),
        migrations.RenameIndex(
            model_name='tokengenerationrow',
            new_name='token_gener_session_bffa59_idx',
            old_name='token_gener_sessio_59c8c9_idx',
        ),
        migrations.RenameIndex(
            model_name='tokengenerationrow',
            new_name='token_gener_session_a3c566_idx',
            old_name='token_gener_sessio_0cb65f_idx',
        ),
        migrations.AlterField(
            model_name='labelgenerationrow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sequencelistitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tokengenerationrow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module_key',
            field=models.CharField(choices=[('application_entry', 'Application Entry'), ('article_management', 'Article Management'), ('base_files', 'Base Files'), ('inventory_planning', 'Inventory Planning'), ('seat_allocation', 'Seat Allocation'), ('sequence_list', 'Sequence List'), ('token_generation', 'Token Generation'), ('labels', 'Labels'), ('reports', 'Reports'), ('order_fund_request', 'Order & Fund Request'), ('purchase_order', 'Purchase Order'), ('audit_logs', 'Audit Logs'), ('user_management', 'User Management')], max_length=64),
        ),
    ]
