# Generated by Django 4.2.29 on 2026-04-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_public_aadhaar_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publicbeneficiaryentry',
            new_name='public_bene_aadhaar_d37a07_idx',
            old_name='public_bene_aadhaar_a8a4ca_idx',
        ),
    ]
