# Generated by Django 4.2.29 on 2026-04-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_application_attachment_temp_linked_flow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationattachment',
            new_name='application_status_731a0e_idx',
            old_name='application_attac_status_9f8eb0_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationattachment',
            new_name='application_form_to_086951_idx',
            old_name='application_attac_form_to_6df95d_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationattachment',
            new_name='application_temp_ex_3c6677_idx',
            old_name='application_attac_temp_ex_f95e2c_idx',
        ),
    ]
