# Generated by Codex on 2026-04-21.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_rename_application_attac_status_9f8eb0_idx_application_status_731a0e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationattachment",
            name="application_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationattachment",
            name="draft_uid",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="applicationattachment",
            name="display_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="applicationattachment",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="applicationattachment",
            name="prefix",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="applicationattachment",
            name="status",
            field=models.CharField(
                choices=[("temp", "Temp"), ("linked", "Linked"), ("missing", "Missing")],
                default="linked",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="applicationattachment",
            index=models.Index(fields=["application_type", "application_id"], name="app_att_type_appid_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationattachment",
            index=models.Index(fields=["application_type", "draft_uid"], name="app_att_type_draft_idx"),
        ),
    ]
