# Generated by Django 4.2.29 on 2026-04-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_attachment_v2_shape'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationattachment',
            new_name='application_applica_7d864c_idx',
            old_name='app_att_type_appid_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationattachment',
            new_name='application_applica_409a5d_idx',
            old_name='app_att_type_draft_idx',
        ),
    ]
