# Generated by Django 4.2.29 on 2026-04-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_rename_app_att_type_appid_idx_application_applica_7d864c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicbeneficiaryhistory",
            name="gender",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="publicbeneficiaryhistory",
            name="gender_status",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="publicbeneficiaryhistory",
            name="handicapped_status",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
