# Generated by Django 4.2.29 on 2026-04-21 12:45

from django.db import migrations, models


def seed_manual_price_mode(apps, schema_editor):
    Article = apps.get_model("core", "Article")
    Article.objects.filter(cost_per_unit=0).update(allow_manual_price=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_publicbeneficiaryhistory_extra_export_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="allow_manual_price",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_manual_price_mode, migrations.RunPython.noop),
    ]
