# Generated by Django 4.2.29 on 2026-04-25 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_othersbeneficiaryentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='othersbeneficiaryentry',
            new_name='others_bene_applica_c25bca_idx',
            old_name='others_bene_applica_9b1842_idx',
        ),
        migrations.RenameIndex(
            model_name='othersbeneficiaryentry',
            new_name='others_bene_status_9386cb_idx',
            old_name='others_bene_status_4fe8a3_idx',
        ),
        migrations.RenameIndex(
            model_name='othersbeneficiaryentry',
            new_name='others_bene_fund_re_131748_idx',
            old_name='others_bene_fund_re_d2b926_idx',
        ),
        migrations.RenameIndex(
            model_name='othersbeneficiaryentry',
            new_name='others_bene_article_755260_idx',
            old_name='others_bene_article_1f059d_idx',
        ),
        migrations.AlterField(
            model_name='applicationattachment',
            name='application_type',
            field=models.CharField(choices=[('district', 'District'), ('public', 'Public'), ('institution', 'Institution'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='othersbeneficiaryentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='othersbeneficiaryentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('archived', 'Archived'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='othersbeneficiaryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
