# Generated by Django 4.2.29 on 2026-04-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_usermodulepermission_can_view_page_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('application_entry', 'Application Entry'), ('article_management', 'Article Management'), ('base_files', 'Base Files'), ('inventory_planning', 'Inventory Planning'), ('seat_allocation', 'Seat Allocation'), ('sequence_list', 'Sequence List'), ('token_generation', 'Token Generation'), ('labels', 'Labels'), ('reports', 'Reports'), ('order_fund_request', 'Order & Fund Request'), ('purchase_order', 'Purchase Order'), ('vendors', 'Vendors'), ('audit_logs', 'Audit Logs'), ('user_management', 'User Management'), ('user_guide', 'User Guide')], max_length=64),
        ),
    ]
